FROM node:20-alpine
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY shared ./shared
COPY packages ./packages
RUN corepack enable && pnpm i && pnpm --filter @cable-platform/validation build && pnpm --filter @cable-platform/contracts build
COPY services/api-gateway ./services/api-gateway
RUN pnpm --filter api-gateway install && pnpm --filter api-gateway build
EXPOSE 8080
CMD ["node","services/api-gateway/src/index.js"]
              