FROM node:20-alpine
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/portal ./apps/portal
RUN corepack enable && pnpm i --filter portal... && pnpm --filter portal build
EXPOSE 5173
CMD ["pnpm","--filter","portal","dev","--host","0.0.0.0"]
