FROM node:20-alpine
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY services/api-gateway ./services/api-gateway
RUN corepack enable && pnpm i --filter api-gateway... && pnpm --filter api-gateway build
EXPOSE 8080
CMD ["pnpm","--filter","api-gateway","start"]
