openapi: 3.0.3
info: { title: Cable Platform API, version: 1.0.0 }
servers: [{ url: http://localhost:8080 }]
paths:
  /health:
    get:
      summary: API health
      responses: { '200': { description: OK } }
  /v1/me:
    get:
      summary: Current user
      security: [{ bearerAuth: [] }]
      responses: { '200': { description: OK } }
  /v1/drc/run:
    post:
      summary: Run DRC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: CableDesign
              type: object
              required: [id, name, cores]
              properties:
                id:
                  type: string
                name:
                  type: string
                cores:
                  type: integer
                  minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: DRCResult
                type: object
                required: [design_id, findings, severity_summary]
                properties:
                  design_id:
                    type: string
                  findings:
                    type: array
                    items:
                      type: object
                      required: [code, message, severity]
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                        severity:
                          type: string
                          enum: [info, warn, error]
                        path:
                          type: string
                  severity_summary:
                    type: object
                    properties:
                      info:
                        type: integer
                      warn:
                        type: integer
                      error:
                        type: integer
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
